In [ ]:
import numpy as np
import matplotlib.pyplot as pyplot
import glob
import cv2
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.7.0


In [ ]:
#!pip install tensorflow-gpu==2.2.0

In [ ]:
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
import os
import seaborn as sns
from keras.applications.vgg16 import VGG16

In [ ]:
#Now we read the input images and assign labels according to the folder names

print(os.listdir("/content/drive/MyDrive/DATASETS/BreastCancerPrediction"))
SIZE=256#Resizing all the images to 256 for VGG16 image feature extraction

['train', 'valid', 'test', 'test1']


In [ ]:
folders=glob.glob('/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/*')
print(folders)

['/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer', '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/1_Cancer']


In [ ]:
#Now we store the training data and labels into respective lists
train_images=[]
train_labels=[]

In [ ]:
for directory_path in glob.glob("/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/*"):
  label=directory_path.split("//")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.png")):
    print(img_path)
    img=cv2.imread(img_path,cv2.IMREAD_COLOR)
    img=cv2.resize(img,(SIZE,SIZE))
    img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
    train_images.append(img)
    train_labels.append(label)

/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8865_idx5_x2451_y2151_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8913_idx5_x501_y101_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8863_idx5_x1451_y1251_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8913_idx5_x301_y801_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8917_idx5_x401_y551_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/9029_idx5_x1601_y851_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/9023_idx5_x2001_y1051_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8914_idx5_x601_y1251_class0.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer/8917_idx5_x1201_y1851_cl

In [ ]:
#Converting to numpy arrays
train_images=np.asarray(train_images)
train_labels=np.asarray(train_labels)

In [ ]:
train_labels

array(['/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer',
       '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer',
       '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/0_NoCancer',
       ...,
       '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/1_Cancer',
       '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/1_Cancer',
       '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/train/1_Cancer'],
      dtype='<U71')

In [ ]:
#Capturing Validation dataset into respective lists

val_images = []
val_labels = [] 

for directory_path in glob.glob("/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/*"):
  label=directory_path.split("//")[-1]
  print(label)
  for img_path in glob.glob(os.path.join(directory_path,"*.png")):
    print(img_path)
    img=cv2.imread(img_path,cv2.IMREAD_COLOR)
    img=cv2.resize(img,(SIZE,SIZE))
    img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
    val_images.append(img)
    val_labels.append(label)

/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8956_idx5_x1101_y201_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/9023_idx5_x1751_y2151_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8975_idx5_x1801_y1201_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8917_idx5_x1551_y351_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8917_idx5_x701_y1101_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8975_idx5_x2001_y1101_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8975_idx5_x1351_y1951_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/8864_idx5_x2301_y2501_class1.png
/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer/9023_idx5_x1351_y1501_class1.png
/content/drive/M

In [ ]:
val_labels

['/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPrediction/test/1_Cancer',
 '/content/drive/MyDrive/DATASETS/BreastCancerPredi

In [ ]:
#Converting to numpy array
val_images=np.asarray(val_images)
val_labels=np.asarray(val_labels)

In [ ]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
le.fit(val_labels)
val_labels_encoded=le.transform(val_labels)
le.fit(train_labels)
train_labels_encoded=le.transform(train_labels)

In [ ]:
print(train_labels_encoded)

[0 0 0 ... 1 1 1]


In [ ]:
#Split the data into training and testing 
x_train,y_train,x_val,y_val=train_images,train_labels_encoded,val_images,val_labels_encoded

In [ ]:
#Normalise the pixel values between 0 to 1 
x_train,x_val=x_train/255.0,x_val/255.0

In [ ]:
print(x_train)

[[[[0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   ...
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]]

  [[0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   ...
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]]

  [[0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   [0.81568627 0.78823529 0.86666667]
   ...
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]
   [0.90980392 0.90980392 0.93333333]]

  ...

  [[0.94901961 0.94901961 0.95294118]
   [0.94901961 0.94901961 0.95294118]
   [0.94901961 0.94901961 0.95294118]
   ...
   [0.94901961 0.94509804 0.95294118]
   [0.94901961 0.94509804 0.95294118]
   [0.94901961 0.94509804 0.95294118]]

  [[0.94901961 0.94901961 0.95294118]
   [0.9

In [ ]:
#Load model into VGG16 without classifier for feature extraction
VGG_model=VGG16(weights='imagenet',include_top=False,input_shape=(SIZE,SIZE,3))

In [ ]:
for layer in VGG_model.layers:
  layer.trainable=False

In [ ]:
VGG_model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 256, 256, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 256, 256, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 256, 256, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 128, 128, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 128, 128, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 128, 128, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 64, 64, 128)       0     

In [ ]:
#Feature Extraction
feature_extractor=VGG_model.predict(x_train)
features=feature_extractor.reshape(feature_extractor.shape[0],-1)

In [ ]:
x_training=features

In [ ]:
from sklearn import svm
model=svm.SVC(kernel='rbf',gamma=0.01)

In [ ]:
model.fit(x_training,train_labels_encoded)

SVC(gamma=0.01)

In [ ]:
#Getting Validation Features
x_val_feature=VGG_model.predict(x_val)
x_val_features=x_val_feature.reshape(x_val_feature.shape[0],-1)

In [ ]:
prediction=model.predict(x_val_features)

In [ ]:
prediction

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn import metrics
print("Accuracy = ", metrics.accuracy_score(prediction,val_labels_encoded))

Accuracy =  0.65


In [ ]:
#from sklearn.model_selection import GridSearchCV
#parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
#grid_search = GridSearchCV(estimator = model,
                           #param_grid = parameters,
                           #scoring = 'accuracy',
                           #cv = 10,
                           #n_jobs = -1)
#grid_search = grid_search.fit(x_training,train_labels_encoded)

In [ ]:
#accuracy = grid_search.best_score_
#grid_search.best_params_